### ISSUE TITLE
Act_10 Proyecto

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-5#1]
Integrantes del equipo: Daisy González Lita, Maribel Santiago Bautsita, Ana Kimberly Hernandez Pérez, Ariadna Monserrat López Aparicio
[Proyecto_equipo_5.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-5/files/10196766/Proyecto_equipo_5.pdf)

**Comment by ARICELCASTRO1999** [comment]
obtuvieron un 36% del 50%

**Comment by Daisy-GonzalezLita12** [comment]
Integrantes del equipo: Daisy González Lita, Maribel Santiago Bautsita, Ana Kimberly Hernandez Pérez, Ariadna Monserrat López Aparicio
el proyecto editado
[Proyecto_equipo_5_editado.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-5/files/10213372/Proyecto_equipo_5_editado.pdf)

**Comment by Jaczibeth** [comment]
Obtuvieron un  de 40.21% del 50%
observaciones : especificar cual es exactamente el nombre de su proyecto
 su delimitaciones no son el adecuado 
no presenta formato APA o si lo presenta no es el adecuado 
falto agregar mas puntos en el marco teórico como las DAPPS , contrato inteligente,NFT.....
confundiste la información de la dependencia con lo de la empresa, La información de la empresa era en dependencia y viceversa.
 No llevaba bibliografías, sin embargo no se tomo en cuenta al momento de calificar.
 

Inge con todo respeto puede checar el trabajo nuevamente y si usted considera que su porcentaje debe ser mas elevado usted podría asignarlo, para evitar malos entendidos. De antemano gracias

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/207433246-9fca7a1f-80c0-41fc-b6b0-fc93e208c03e.png)
Hace falta informacion de una dependencia

**Comment by josealfredo79** [comment]
No tiene creditos APA

![image](https://user-images.githubusercontent.com/58342642/207433493-f6d46216-0174-424f-a547-e1d470d54566.png)

**Comment by josealfredo79** [comment]
Favor de checar su trabajo

**Comment by josealfredo79** [comment]
Revisado...
